project_id = "grlyhylqbekhrmfwgyme"

[functions.create-first-admin]
verify_jwt = false

[functions.evolution]
verify_jwt = false

[functions.support-login]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true
