project_id = "grlyhylqbekhrmfwgyme"

[functions.create-first-admin]
verify_jwt = false

[functions.evolution]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false

[functions.support-login]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = true

[functions.set-whatsapp-webhook]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.create-admin]
verify_jwt = true

[functions.delete-admin]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.ai-direct-chat]
verify_jwt = false

[functions.start-bot-chat]
verify_jwt = false

[functions.send-agent-message]
verify_jwt = false

[functions.get-attendance-messages]
verify_jwt = false

[functions.create-whatsapp-instance]
verify_jwt = true

[functions.get-whatsapp-qrcode]
verify_jwt = true

[functions.check-whatsapp-status]
verify_jwt = true

[functions.delete-whatsapp-instance]
verify_jwt = true

[functions.logout-whatsapp-instance]
verify_jwt = true

# Newly ensured public endpoints for support-side contact loading
[functions.get-connected-whatsapp-instance]
verify_jwt = false

[functions.get-whatsapp-contacts]
verify_jwt = false

[functions.get-whatsapp-chats]
verify_jwt = false

[functions.get-whatsapp-messages]
verify_jwt = false

# Keep sync protected (admin-side)
[functions.sync-whatsapp-contacts]
verify_jwt = true
